name: Create release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: script/build-in-docker.sh make prep-release
      - id: get-tag
        run: |
          tag=$(echo ${{ github.ref }} | cut -d/ -f3)
          echo "::set-output name=tag::$tag"
      - id: get-version
        run: |
          version=$(echo ${{ steps.get-tag.outputs.tag }} | cut -c 2-)
          echo "::set-output name=version::$version"
      - id: pom-version
        run: |
          version=$(make print-version)
          echo "::set-output name=version::$version"
      - name: Ensure version consistency
        run: ${{ steps.get-version.outputs.version == steps.pom-version.outputs.version }}
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag.outputs.tag }}
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
          files: |
            build/fluree-${{ steps.get-version.outputs.version }}.zip
            build/fluree-${{ steps.get-version.outputs.version }}.zip.sha256
